ALTER Table [Individual_Location]
ALTER COLUMN type_ varchar(10) null


CREATE NONCLUSTERED INDEX IX_Indiv_locaction_type_ID ON [dbo].[Individual_Location]
(
	[ID] ASC,
	[type_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


